### ISSUE TITLE
How to use Preheat with swift 2.3

### ISSUE THREAD

**Issue by raviatri** [kean/Preheat#8]
Hello kean thanks for this great library i tested it on swift 3.0 and it is great library great experience.
But i have to integrate this with my project written in swift 2.3 and i tried a lot but failed. Is it possible to use this with swift 2.3?

Thanks

**Comment by kean** [comment]
You can use previous version ([Preheat 2.0](https://github.com/kean/Preheat/releases/tag/2.0)), it is written in Swift 2.2. But I would recommend to update your own project to Swift 3, because [Swift 2.3 is deprecated](https://twitter.com/kostiakoval/status/793335735315230721?lang=en) and Xcode 8.2 is that last release that supports it.

**Comment by raviatri** [comment]
Thanks a lot kean thanks for the advice, yeah i know and i will updated my project to swift 3.0 before next release.
